"use client";

import { useEffect, useState } from "react";
import { apiFetch, ApiError } from "@/lib/api";
import { getRole, isAdmin } from "@/lib/auth";
import type { AdminUser, AuditLogEntry } from "@/lib/types";

const ROLES = ["admin", "analyst", "viewer"] as const;
const AUDIT_RANGES = ["24h", "7d", "30d"];
const PAGE_SIZE = 8;

// Solid-color + tinted-pill palette shared by avatars and role pills, cycled by a hash of the
// user's email so each person gets a stable (not random-per-render) color.
const PALETTE = {
  blue: { fg: "var(--blue)", bg: "rgba(88,166,255,.12)", border: "rgba(88,166,255,.35)" },
  purple: { fg: "var(--purple)", bg: "rgba(188,140,255,.12)", border: "rgba(188,140,255,.35)" },
  green: { fg: "var(--green)", bg: "rgba(63,185,80,.12)", border: "rgba(63,185,80,.35)" },
  amber: { fg: "var(--amber)", bg: "rgba(227,179,65,.12)", border: "rgba(227,179,65,.35)" },
  red: { fg: "var(--red)", bg: "rgba(248,81,73,.12)", border: "rgba(248,81,73,.35)" },
} as const;
type PaletteKey = keyof typeof PALETTE;
const AVATAR_KEYS = Object.keys(PALETTE) as PaletteKey[];
const ROLE_PALETTE: Record<string, PaletteKey> = { admin: "purple", analyst: "blue", viewer: "amber" };

function avatarKey(seed: string): PaletteKey {
  let hash = 0;
  for (let i = 0; i < seed.length; i++) hash = (hash * 31 + seed.charCodeAt(i)) >>> 0;
  return AVATAR_KEYS[hash % AVATAR_KEYS.length];
}

function randomPassword(len = 14): string {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%";
  const bytes = new Uint32Array(len);
  crypto.getRandomValues(bytes);
  return Array.from(bytes, (n) => chars[n % chars.length]).join("");
}

export default function UsersPage() {
  const role = getRole();
  const admin = isAdmin(role);

  const [users, setUsers] = useState<AdminUser[] | null>(null);
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [userRole, setUserRole] = useState<(typeof ROLES)[number]>("viewer");
  const [analystTier, setAnalystTier] = useState<string>("");
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [generated, setGenerated] = useState<{ email: string; password: string } | null>(null);
  const [copiedGenerated, setCopiedGenerated] = useState(false);

  const [search, setSearch] = useState("");
  const [roleFilter, setRoleFilter] = useState("all");
  const [userFilterOpen, setUserFilterOpen] = useState(false);
  const [usersPage, setUsersPage] = useState(1);

  const [auditLog, setAuditLog] = useState<AuditLogEntry[] | null>(null);
  const [auditRange, setAuditRange] = useState("7d");
  const [auditRangeOpen, setAuditRangeOpen] = useState(false);
  const [actionFilter, setActionFilter] = useState("all");
  const [auditPage, setAuditPage] = useState(1);

  async function load() {
    setUsers(await apiFetch<AdminUser[]>("/api/users"));
  }

  useEffect(() => { load(); }, []);
  useEffect(() => {
    apiFetch<AuditLogEntry[]>(`/api/audit-log?range=${auditRange}`).then(setAuditLog).catch(() => setAuditLog([]));
  }, [auditRange]);
  useEffect(() => { setUsersPage(1); }, [search, roleFilter, users]);
  useEffect(() => { setAuditPage(1); }, [actionFilter, auditLog]);

  async function createUser() {
    setError(null);
    setGenerated(null);
    if (!email.trim()) {
      setError("Email is required.");
      return;
    }
    const autoGenerated = !password.trim();
    const pwd = autoGenerated ? randomPassword() : password;
    setBusy(true);
    try {
      await apiFetch("/api/users", {
        method: "POST",
        body: JSON.stringify({
          email: email.trim(), password: pwd, role: userRole,
          analyst_tier: analystTier ? Number(analystTier) : null,
        }),
      });
      if (autoGenerated) setGenerated({ email: email.trim(), password: pwd });
      setEmail(""); setPassword(""); setUserRole("viewer"); setAnalystTier("");
      await load();
    } catch (e) {
      setError(e instanceof ApiError ? e.message : "Failed to create user.");
    } finally {
      setBusy(false);
    }
  }

  async function patchUser(id: string, body: { role?: string; analyst_tier?: number | null }) {
    await apiFetch(`/api/users/${id}`, { method: "PATCH", body: JSON.stringify(body) });
    await load();
  }

  const [deletingId, setDeletingId] = useState<string | null>(null);

  async function deleteUser(u: AdminUser) {
    if (!window.confirm(`Delete user ${u.email}? This cannot be undone.`)) return;
    setError(null);
    setDeletingId(u.id);
    try {
      await apiFetch(`/api/users/${u.id}`, { method: "DELETE" });
      await load();
    } catch (e) {
      setError(e instanceof ApiError ? e.message : "Failed to delete user.");
    } finally {
      setDeletingId(null);
    }
  }

  async function copyGenerated() {
    if (!generated) return;
    await navigator.clipboard.writeText(generated.password);
    setCopiedGenerated(true);
    setTimeout(() => setCopiedGenerated(false), 1200);
  }

  const filteredUsers = (users ?? []).filter(
    (u) => (roleFilter === "all" || u.role === roleFilter) &&
      (!search.trim() || u.email.toLowerCase().includes(search.trim().toLowerCase()))
  );
  const totalUserPages = Math.max(1, Math.ceil(filteredUsers.length / PAGE_SIZE));
  const pagedUsers = filteredUsers.slice((usersPage - 1) * PAGE_SIZE, usersPage * PAGE_SIZE);

  const uniqueActions = Array.from(new Set((auditLog ?? []).map((e) => e.action))).sort();
  const filteredAudit = (auditLog ?? []).filter((e) => actionFilter === "all" || e.action === actionFilter);
  const totalAuditPages = Math.max(1, Math.ceil(filteredAudit.length / PAGE_SIZE));
  const pagedAudit = filteredAudit.slice((auditPage - 1) * PAGE_SIZE, auditPage * PAGE_SIZE);

  return (
    <div>
      <div style={{ display: "flex", alignItems: "center", gap: 14, marginBottom: 22 }}>
        <div
          style={{
            width: 42, height: 42, borderRadius: 10, background: "rgba(88,166,255,.12)",
            border: "1px solid rgba(88,166,255,.28)", display: "flex", alignItems: "center",
            justifyContent: "center", color: "var(--blue)", flexShrink: 0,
          }}
        >
          <PeopleIcon />
        </div>
        <div>
          <div style={{ fontSize: 18, fontWeight: 700 }}>User & Access Management</div>
          <div style={{ fontSize: 11.5, color: "var(--muted)", marginTop: 3 }}>
            Manage analyst accounts, roles, and Tier 1/2/3 assignment routing labels.
          </div>
        </div>
      </div>

      {admin && (
        <Box icon={<UserPlusIcon />} title="Create User" accent>
          <div style={{ display: "flex", flexWrap: "wrap", gap: 12, alignItems: "flex-end" }}>
            <IconField label="Email" icon={<MailIcon />}>
              <input value={email} onChange={(e) => setEmail(e.target.value)} placeholder="e.g. analyst@example.com" style={iconInputStyle} />
            </IconField>
            <IconField label="Temporary Password" icon={<KeyIcon />}>
              <div style={{ position: "relative" }}>
                <input
                  value={password} onChange={(e) => setPassword(e.target.value)}
                  type={showPassword ? "text" : "password"} placeholder="Auto-generated"
                  style={{ ...iconInputStyle, paddingRight: 32, width: 190 }}
                />
                <button
                  type="button" onClick={() => setShowPassword((s) => !s)}
                  title={showPassword ? "Hide" : "Show"}
                  style={{
                    position: "absolute", right: 6, top: "50%", transform: "translateY(-50%)",
                    background: "transparent", border: "none", color: "var(--dim)", cursor: "pointer", display: "flex", padding: 3,
                  }}
                >
                  {showPassword ? <EyeOffIcon /> : <EyeIcon />}
                </button>
              </div>
            </IconField>
            <Field label="Role">
              <select value={userRole} onChange={(e) => setUserRole(e.target.value as (typeof ROLES)[number])} style={inputStyle}>
                {ROLES.map((r) => <option key={r} value={r}>{r[0].toUpperCase() + r.slice(1)}</option>)}
              </select>
            </Field>
            <Field label="Analyst Tier">
              <select value={analystTier} onChange={(e) => setAnalystTier(e.target.value)} style={inputStyle}>
                <option value="">None</option>
                <option value="1">Tier 1</option>
                <option value="2">Tier 2</option>
                <option value="3">Tier 3</option>
              </select>
            </Field>
            <button onClick={createUser} disabled={busy} style={btnStyle} className="transition-accent">
              <UserPlusIcon size={13} /> {busy ? "Creating..." : "Create User"}
            </button>
          </div>
          {error && <div style={{ color: "var(--red)", fontSize: 11, marginTop: 10 }}>{error}</div>}

          {generated && (
            <div
              className="fade-in-up"
              style={{
                display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, marginTop: 12,
                padding: "10px 14px", background: "rgba(63,185,80,.08)", border: "1px solid rgba(63,185,80,.28)", borderRadius: 8,
              }}
            >
              <div style={{ display: "flex", alignItems: "center", gap: 10, minWidth: 0 }}>
                <span style={{ color: "var(--green)", display: "flex", flexShrink: 0 }}><CheckIcon /></span>
                <div style={{ fontSize: 11.5, minWidth: 0 }}>
                  Generated password for <strong>{generated.email}</strong>:{" "}
                  <span style={{ fontFamily: "var(--mono)", color: "var(--text)" }}>{generated.password}</span>
                  <div style={{ fontSize: 10, color: "var(--dim)", marginTop: 2 }}>Copy it now — it won't be shown again.</div>
                </div>
              </div>
              <div style={{ display: "flex", gap: 6, flexShrink: 0 }}>
                <button onClick={copyGenerated} style={smallIconBtnStyle(copiedGenerated ? "green" : undefined)} className="transition-accent">
                  {copiedGenerated ? <CheckIcon /> : <ClipboardIcon />}
                </button>
                <button onClick={() => setGenerated(null)} style={smallIconBtnStyle()} className="transition-accent">×</button>
              </div>
            </div>
          )}

          <div style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 10, color: "var(--dim)", marginTop: 10 }}>
            <InfoIcon /> New users are forced to change their password on first login. Leave the password field blank to auto-generate one.
          </div>
        </Box>
      )}

      <Box
        icon={<PeopleIcon size={14} />}
        title={`Users ${users ? `(${filteredUsers.length})` : ""}`}
        right={
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <div style={{ position: "relative" }}>
              <span style={{ position: "absolute", left: 9, top: "50%", transform: "translateY(-50%)", color: "var(--dim)", display: "flex", pointerEvents: "none" }}>
                <SearchIcon />
              </span>
              <input
                value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search users..."
                style={{ ...inputStyle, paddingLeft: 28, width: 170 }}
              />
            </div>
            <div style={{ position: "relative" }}>
              <button onClick={() => setUserFilterOpen((o) => !o)} style={filterBtnStyle(roleFilter !== "all" || userFilterOpen)} className="transition-accent" title="Filter by role">
                <FilterIcon />
              </button>
              {userFilterOpen && (
                <div className="fade-in-up" style={dropdownPanelStyle}>
                  {["all", ...ROLES].map((r) => (
                    <button
                      key={r} onClick={() => { setRoleFilter(r); setUserFilterOpen(false); }}
                      style={dropdownItemStyle(roleFilter === r)} className="row-hover"
                    >
                      {r === "all" ? "All Roles" : r[0].toUpperCase() + r.slice(1)}
                    </button>
                  ))}
                </div>
              )}
            </div>
          </div>
        }
      >
        <div style={{ overflowX: "auto" }}>
          <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 12 }}>
            <thead>
              <tr>
                {["Email", "Role", "Analyst Tier", "Created", ...(admin ? ["Actions"] : [])].map((h) => (
                  <th key={h} style={{ textAlign: "left", padding: "8px 10px", fontSize: 10, textTransform: "uppercase", color: "var(--muted)", borderBottom: "1px solid var(--border)" }}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {users === null ? (
                <tr><td colSpan={5} style={{ padding: 20, textAlign: "center", color: "var(--dim)" }}>Loading...</td></tr>
              ) : pagedUsers.length === 0 ? (
                <tr><td colSpan={5} style={{ padding: 20, textAlign: "center", color: "var(--dim)" }}>No users match this filter</td></tr>
              ) : pagedUsers.map((u) => (
                <tr key={u.id} className="row-hover">
                  <td style={cellStyle}>
                    <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                      <UserAvatar email={u.email} />
                      {u.email}
                    </div>
                  </td>
                  <td style={cellStyle}>
                    {admin ? (
                      <select
                        id={`role-${u.id}`} value={u.role}
                        onChange={(e) => patchUser(u.id, { role: e.target.value })}
                        style={pillSelectStyle(PALETTE[ROLE_PALETTE[u.role] ?? "blue"])}
                      >
                        {ROLES.map((r) => <option key={r} value={r}>{r[0].toUpperCase() + r.slice(1)}</option>)}
                      </select>
                    ) : (
                      <RolePill role={u.role} />
                    )}
                  </td>
                  <td style={cellStyle}>
                    {admin ? (
                      <select
                        value={u.analyst_tier ?? ""}
                        onChange={(e) => patchUser(u.id, { analyst_tier: e.target.value ? Number(e.target.value) : null })}
                        style={pillSelectStyle(null)}
                      >
                        <option value="">None</option>
                        <option value="1">Tier 1</option>
                        <option value="2">Tier 2</option>
                        <option value="3">Tier 3</option>
                      </select>
                    ) : (
                      <span style={{ ...tierPillStyle, cursor: "default" }}>{u.analyst_tier ? `Tier ${u.analyst_tier}` : "None"}</span>
                    )}
                  </td>
                  <td style={cellStyle}>{new Date(u.created_at).toLocaleDateString()}</td>
                  {admin && (
                    <td style={cellStyle}>
                      <div style={{ display: "flex", gap: 6 }}>
                        <button
                          onClick={() => document.getElementById(`role-${u.id}`)?.focus()}
                          title="Edit role / tier"
                          style={iconActionBtnStyle("blue")} className="transition-accent"
                        >
                          <PencilIcon />
                        </button>
                        <button
                          onClick={() => deleteUser(u)}
                          disabled={deletingId === u.id}
                          title="Delete user"
                          style={{ ...iconActionBtnStyle("red"), opacity: deletingId === u.id ? 0.5 : 1 }}
                          className="transition-accent"
                        >
                          <TrashIcon />
                        </button>
                      </div>
                    </td>
                  )}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
        {users !== null && (
          <Pagination page={usersPage} totalPages={totalUserPages} total={filteredUsers.length} pageSize={PAGE_SIZE} onPage={setUsersPage} noun="users" />
        )}
      </Box>

      <Box
        icon={<ShieldIcon />}
        title="Audit Log"
        right={
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <select value={actionFilter} onChange={(e) => setActionFilter(e.target.value)} style={inputStyle}>
              <option value="all">All Actions</option>
              {uniqueActions.map((a) => <option key={a} value={a}>{a}</option>)}
            </select>
            <div style={{ position: "relative" }}>
              <button onClick={() => setAuditRangeOpen((o) => !o)} style={filterBtnStyle(auditRangeOpen)} className="transition-accent" title="Filter by time range">
                <FilterIcon />
              </button>
              {auditRangeOpen && (
                <div className="fade-in-up" style={dropdownPanelStyle}>
                  {AUDIT_RANGES.map((r) => (
                    <button
                      key={r} onClick={() => { setAuditRange(r); setAuditRangeOpen(false); }}
                      style={dropdownItemStyle(auditRange === r)} className="row-hover"
                    >
                      Last {r}
                    </button>
                  ))}
                </div>
              )}
            </div>
          </div>
        }
      >
        <div style={{ overflowX: "auto" }}>
          <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 12 }}>
            <thead>
              <tr>
                {["Time", "Actor", "Action", "Target", "Details"].map((h) => (
                  <th key={h} style={{ textAlign: "left", padding: "8px 10px", fontSize: 10, textTransform: "uppercase", color: "var(--muted)", borderBottom: "1px solid var(--border)" }}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {auditLog === null ? (
                <tr><td colSpan={5} style={{ padding: 20, textAlign: "center", color: "var(--dim)" }}>Loading...</td></tr>
              ) : pagedAudit.length === 0 ? (
                <tr><td colSpan={5} style={{ padding: 20, textAlign: "center", color: "var(--dim)" }}>No audit entries in this range</td></tr>
              ) : (
                pagedAudit.map((entry) => (
                  <tr key={entry.id} className="row-hover">
                    <td style={cellStyle}>
                      <div style={{ display: "flex", alignItems: "center", gap: 7 }}>
                        <span style={{ width: 6, height: 6, borderRadius: "50%", background: actionColor(entry.action).fg, flexShrink: 0 }} />
                        {new Date(entry.created_at).toLocaleString()}
                      </div>
                    </td>
                    <td style={cellStyle}>
                      <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                        <UserAvatar email={users?.find((u) => u.id === entry.actor_id)?.email ?? "?"} size={20} />
                        {users?.find((u) => u.id === entry.actor_id)?.email ?? entry.actor_id}
                      </div>
                    </td>
                    <td style={{ ...cellStyle, color: actionColor(entry.action).fg, fontWeight: 600 }}>{entry.action}</td>
                    <td style={cellStyle}>{entry.target_type} · <span style={{ fontFamily: "var(--mono)", fontSize: 10 }}>{entry.target_id.slice(0, 8)}</span></td>
                    <td style={{ ...cellStyle, fontFamily: "var(--mono)", fontSize: 10, color: "var(--muted)" }}>{JSON.stringify(entry.details)}</td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
        {auditLog !== null && (
          <Pagination page={auditPage} totalPages={totalAuditPages} total={filteredAudit.length} pageSize={PAGE_SIZE} onPage={setAuditPage} noun="logs" />
        )}
      </Box>
    </div>
  );
}

function actionColor(action: string): { fg: string } {
  if (action.includes("deleted")) return { fg: "var(--red)" };
  if (action.includes("created")) return { fg: "var(--green)" };
  return { fg: "var(--blue)" };
}

function UserAvatar({ email, size = 26 }: { email: string; size?: number }) {
  const p = PALETTE[avatarKey(email)];
  return (
    <div
      style={{
        width: size, height: size, borderRadius: "50%", background: p.fg, color: "#fff",
        display: "flex", alignItems: "center", justifyContent: "center", fontSize: size * 0.44, fontWeight: 700, flexShrink: 0,
      }}
    >
      {email[0]?.toUpperCase() ?? "?"}
    </div>
  );
}

function RolePill({ role }: { role: string }) {
  const p = PALETTE[ROLE_PALETTE[role] ?? "blue"];
  return (
    <span
      style={{
        display: "inline-block", background: p.bg, border: `1px solid ${p.border}`, borderRadius: 6,
        padding: "5px 10px", color: p.fg, fontFamily: "var(--mono)", fontSize: 11.5, fontWeight: 600, textTransform: "capitalize",
      }}
    >
      {role}
    </span>
  );
}

function Pagination({
  page, totalPages, total, pageSize, onPage, noun,
}: { page: number; totalPages: number; total: number; pageSize: number; onPage: (p: number) => void; noun: string }) {
  const from = total === 0 ? 0 : (page - 1) * pageSize + 1;
  const to = Math.min(page * pageSize, total);
  return (
    <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginTop: 12, fontSize: 11, color: "var(--dim)" }}>
      <span>Showing {from} to {to} of {total} {noun}</span>
      <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
        <button onClick={() => onPage(page - 1)} disabled={page <= 1} style={pageBtnStyle(page <= 1)} className="transition-accent"><ChevronLeftIcon /></button>
        <span style={{
          minWidth: 22, textAlign: "center", padding: "3px 8px", background: "var(--raised)",
          border: "1px solid var(--border)", borderRadius: 6, color: "var(--text)", fontWeight: 600,
        }}>{page}</span>
        <button onClick={() => onPage(page + 1)} disabled={page >= totalPages} style={pageBtnStyle(page >= totalPages)} className="transition-accent"><ChevronRightIcon /></button>
      </div>
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <div style={labelStyle}>{label}</div>
      {children}
    </div>
  );
}

function IconField({ label, icon, children }: { label: string; icon: React.ReactNode; children: React.ReactNode }) {
  return (
    <div>
      <div style={labelStyle}>{label}</div>
      <div style={{ position: "relative" }}>
        <span style={{ position: "absolute", left: 9, top: "50%", transform: "translateY(-50%)", color: "var(--dim)", display: "flex", pointerEvents: "none" }}>
          {icon}
        </span>
        {children}
      </div>
    </div>
  );
}

function Box({
  icon, title, right, accent, children,
}: { icon?: React.ReactNode; title: string; right?: React.ReactNode; accent?: boolean; children: React.ReactNode }) {
  return (
    <div
      className="card-hover"
      style={{
        background: accent ? "rgba(88,166,255,.04)" : "var(--surf)",
        border: `1px solid ${accent ? "rgba(88,166,255,.3)" : "var(--border)"}`,
        borderRadius: 10, padding: 16, marginBottom: 16, boxShadow: "var(--shadow-card)",
      }}
    >
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, marginBottom: 14, flexWrap: "wrap" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 7, fontSize: 11, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.07em", color: "var(--blue)" }}>
          {icon}{title}
        </div>
        {right}
      </div>
      {children}
    </div>
  );
}

// --- icons -----------------------------------------------------------------------------------

function PeopleIcon({ size = 20 }: { size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <path d="M9 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM3 20c0-3.3 2.7-6 6-6s6 2.7 6 6M17 11a3 3 0 1 0 0-6M21 20c0-2.5-1.6-4.6-4-5.4" />
    </svg>
  );
}

function UserPlusIcon({ size = 16 }: { size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <path d="M9 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM2 20c0-3.3 2.7-6 7-6s7 2.7 7 6M19 8v6M22 11h-6" />
    </svg>
  );
}

function MailIcon() {
  return (
    <svg width={13} height={13} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <rect x="2" y="4" width="20" height="16" rx="2" />
      <path d="m2 7 10 6 10-6" />
    </svg>
  );
}

function KeyIcon() {
  return (
    <svg width={13} height={13} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <circle cx="7.5" cy="15.5" r="4.5" />
      <path d="m10.6 12.4 8.9-8.9M17 8l2 2M20 5l2 2" />
    </svg>
  );
}

function EyeIcon() {
  return (
    <svg width={14} height={14} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7-10-7-10-7Z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  );
}

function EyeOffIcon() {
  return (
    <svg width={14} height={14} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <path d="M17.9 17.9A10.4 10.4 0 0 1 12 20c-6.5 0-10-7-10-7a18.4 18.4 0 0 1 4.2-5.2M9.9 5.2A9.7 9.7 0 0 1 12 5c6.5 0 10 7 10 7a18.5 18.5 0 0 1-2.2 3.1M14.1 14.1a3 3 0 1 1-4.2-4.2" />
      <path d="M2 2l20 20" />
    </svg>
  );
}

function SearchIcon() {
  return (
    <svg width={13} height={13} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <circle cx="11" cy="11" r="7" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}

function FilterIcon() {
  return (
    <svg width={13} height={13} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <path d="M4 4h16l-6 8.5V19l-4 2v-8.5L4 4Z" />
    </svg>
  );
}

function PencilIcon() {
  return (
    <svg width={13} height={13} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <path d="M12 20h9M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4Z" />
    </svg>
  );
}

function TrashIcon() {
  return (
    <svg width={13} height={13} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <path d="M3 6h18M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2m3 0-1 14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2L4 6h16Z" />
    </svg>
  );
}

function ChevronLeftIcon() {
  return (
    <svg width={13} height={13} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.2} strokeLinecap="round" strokeLinejoin="round">
      <path d="m15 18-6-6 6-6" />
    </svg>
  );
}

function ChevronRightIcon() {
  return (
    <svg width={13} height={13} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.2} strokeLinecap="round" strokeLinejoin="round">
      <path d="m9 18 6-6-6-6" />
    </svg>
  );
}

function CheckIcon() {
  return (
    <svg width={13} height={13} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2.5} strokeLinecap="round" strokeLinejoin="round">
      <path d="M20 6 9 17l-5-5" />
    </svg>
  );
}

function ClipboardIcon() {
  return (
    <svg width={13} height={13} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <rect x="8" y="2" width="8" height="4" rx="1" />
      <path d="M16 4h2a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h2" />
    </svg>
  );
}

function InfoIcon() {
  return (
    <svg width={12} height={12} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <circle cx="12" cy="12" r="9" />
      <path d="M12 11v6M12 8h.01" />
    </svg>
  );
}

function ShieldIcon({ size = 14 }: { size?: number }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <path d="M12 3l7 3v5c0 5-3.2 8.4-7 10-3.8-1.6-7-5-7-10V6l7-3Z" />
      <path d="M9 12l2 2 4-4" />
    </svg>
  );
}

// --- styles ------------------------------------------------------------------------------------

const cellStyle: React.CSSProperties = { padding: "8px 10px", borderBottom: "1px solid var(--raised)" };

const labelStyle: React.CSSProperties = { fontSize: 9, color: "var(--dim)", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 4 };

const inputStyle: React.CSSProperties = {
  background: "var(--raised)", border: "1px solid var(--border)", borderRadius: 5,
  padding: "6px 9px", color: "var(--text)", fontFamily: "var(--mono)", fontSize: 12, outline: "none",
};

const iconInputStyle: React.CSSProperties = { ...inputStyle, paddingLeft: 28, width: 190 };

const btnStyle: React.CSSProperties = {
  display: "flex", alignItems: "center", gap: 6, padding: "7px 14px", background: "rgba(88,166,255,.1)",
  border: "1px solid rgba(88,166,255,.26)", borderRadius: 5, color: "var(--blue)", fontSize: 12, fontWeight: 500,
  cursor: "pointer", whiteSpace: "nowrap",
};

const tierPillStyle: React.CSSProperties = {
  background: "var(--raised)", border: "1px solid var(--border)", borderRadius: 6,
  padding: "5px 10px", color: "var(--muted)", fontFamily: "var(--mono)", fontSize: 11.5, fontWeight: 600, display: "inline-block",
};

function pillSelectStyle(p: { fg: string; bg: string; border: string } | null): React.CSSProperties {
  const c = p ?? { fg: "var(--muted)", bg: "var(--raised)", border: "var(--border)" };
  return {
    background: c.bg, border: `1px solid ${c.border}`, borderRadius: 6, padding: "5px 9px",
    color: c.fg, fontFamily: "var(--mono)", fontSize: 11.5, fontWeight: 600, outline: "none",
    cursor: "pointer", minWidth: 90, textTransform: "capitalize",
  };
}

function iconActionBtnStyle(kind: "blue" | "red"): React.CSSProperties {
  const c = kind === "red" ? { fg: "var(--red)", bg: "rgba(248,81,73,.08)", border: "rgba(248,81,73,.3)" } : { fg: "var(--blue)", bg: "rgba(88,166,255,.08)", border: "rgba(88,166,255,.26)" };
  return {
    display: "flex", alignItems: "center", justifyContent: "center", width: 28, height: 28,
    background: c.bg, border: `1px solid ${c.border}`, color: c.fg, borderRadius: 5, cursor: "pointer",
  };
}

function smallIconBtnStyle(highlight?: "green"): React.CSSProperties {
  return {
    display: "flex", alignItems: "center", justifyContent: "center", width: 26, height: 26,
    background: "transparent", border: "1px solid var(--border)", borderRadius: 6,
    color: highlight === "green" ? "var(--green)" : "var(--dim)", cursor: "pointer", fontSize: 14,
  };
}

function filterBtnStyle(active: boolean): React.CSSProperties {
  return {
    display: "flex", alignItems: "center", justifyContent: "center", width: 30, height: 30,
    background: active ? "rgba(88,166,255,.14)" : "var(--raised)",
    border: `1px solid ${active ? "rgba(88,166,255,.35)" : "var(--border)"}`,
    borderRadius: 6, color: active ? "var(--blue)" : "var(--muted)", cursor: "pointer",
  };
}

function pageBtnStyle(disabled: boolean): React.CSSProperties {
  return {
    display: "flex", alignItems: "center", justifyContent: "center", width: 26, height: 26,
    background: "var(--raised)", border: "1px solid var(--border)", borderRadius: 6,
    color: disabled ? "var(--dim)" : "var(--muted)", cursor: disabled ? "default" : "pointer", opacity: disabled ? 0.5 : 1,
  };
}

const dropdownPanelStyle: React.CSSProperties = {
  position: "absolute", top: "calc(100% + 6px)", right: 0, minWidth: 140, background: "var(--surf)",
  border: "1px solid var(--border)", borderRadius: 8, boxShadow: "var(--shadow-card)", zIndex: 20, overflow: "hidden", padding: 4,
};

function dropdownItemStyle(active: boolean): React.CSSProperties {
  return {
    display: "block", width: "100%", textAlign: "left", padding: "7px 10px", borderRadius: 5,
    background: active ? "rgba(88,166,255,.12)" : "transparent", border: "none",
    color: active ? "var(--blue)" : "var(--text)", fontSize: 12, cursor: "pointer",
  };
}
